---

image: "python:3.7"

before_script:
  - export HTTP_PROXY=http://proxy.sbb.spk-berlin.de:3128
  - export HTTPS_PROXY=http://proxy.sbb.spk-berlin.de:3128
  - python --version
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

stages:
  - analysis
  - test


linting:
  stage: analysis
  script:
    - flake8 --exit-zero --statistics --doctests ocrd_butler/ tests/

tests:
  stage: test
  script:
    - export PROFILE=test
    - pytest tests --doctest-modules ocrd_butler
    - coverage xml
  coverage: '/^TOTAL\s+\d+\s+\d+\s+\d+\s+\d+\s+(\d+\%)/'
  artifacts:
    when: always
    paths:
      - coverage.xml
      - test-report.xml
    reports:
      junit: test-report.xml
      cobertura: coverage.xml
    expire_in: 80 weeks

...
