# Config file for automatic testing at travis-ci.org
language: python
dist: bionic
python:
  - "3.7"
  - "3.6"
  - "3.5"

before_install:
  - source ~/virtualenv/python3.7/bin/activate
  - git clone https://github.com/OCR-D/ocrd_all.git ocrd_all
  - cd ocrd_all
  - sudo apt-get -qq update
  - sudo make deps-ubuntu
  - make all
  - cd ..

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox-travis
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

# Command to run tests, e.g. python setup.py test
script: tox
