---
## This is currently just an example, not implemented yet.
format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
datefmt: "%Y-%m-%d %H:%M:%S"
logger_path: /data/log/ocrd-butler.log
rotation: "06:00"
backupCount: 20
encoding: utf8